runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '35.192.157.243'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'Colmilav2022*'
  INSTANCE_CONNECTION_NAME: '<instance_identifier>'

beta_settings:
  cloud_sql_instances: '<instance_identifier>'
